### ISSUE TITLE
Incompatible with the Node.js version

### ISSUE THREAD

**Issue by unsown** [keybase/python-triplesec#15]
The message in the following command is generated in the page https://keybase.io/triplesec/ with the key: "abc". It is failed to be decrypted with the command:
triplesec dec 1c94d7de000000036a30a8b14da5fc0ec86a24287c1ad85a946bb9e77ce6afd7ad49a37f810cdccf2e28809ec914c5dfd8390777f0b5c3035c77bd15d75df604ebcabfdb571a2a25cedf5d831546eff85e64e28f26877e46c746683b415ee5d2a964a4115a54e30a26afbe4ae57e08c8867ee523e01b51c847a5d1912857059fcce34cd4e2fc4e092bc20e06daa138fa051a75b3d12111187bd6cfad31ea45edb455818d1319d3cc1e99811ccfe18c9e5f3c03745456cb0e3593a2ce8456913579346425df9cb7ed91824b7f871ea6b223f749cb6e517996

**Comment by mfrager** [comment]
The fork in Pull Request #17 is compatible with the Node.JS TripleSec implementation. However, the "Magical In-Browser" test is not compatible with either and seems to be broken somehow from the actual TripleSec specification.
